;(function () {

    var Module = {};
    var root = this;

    if (typeof exports !== 'undefined'){
	    module.exports = Module;
    }else{
        root.libotr3Module = Module;
    }

// -- code generated by emscripten will follow ---
